spring.application.name=api-externa-backend
spring.profiles.active=test

# URL base de cada API externa
api.cep.url=https://viacep.com.br
api.brapi.url=https://brapi.dev
api.cnpj.url=https://brasilapi.com.br/api


api.brapi.token=${BRAPI_TOKEN}

# application-local.properties
api.brapi.token=k6iKbDWPvuWyxUj3f8C4J3
